from typing import Any

def CGEventCreate(source: Any) -> Any | None: ...
def CGEventCreateKeyboardEvent(source: Any, virtualKey: int, keyDown: bool) -> Any: ...
def CGEventCreateMouseEvent(source: Any, mouseType: int, mouseCursorPosition: tuple[float, float], mouseButton: int) -> Any: ...
def CGEventGetIntegerValueField(event: Any, field: int) -> int: ...
def CGEventGetLocation(event: Any) -> Any: ...
def CGEventPost(tap: int, event: Any) -> None: ...
def CGEventSetFlags(event: Any, flags: int) -> None: ...

kCGEventFlagMaskShift: int
kCGEventLeftMouseDown: int
kCGEventLeftMouseUp: int
kCGEventMouseMoved: int
kCGEventSourceStateID: int
kCGHIDEventTap: int
